server:
  port: 9001

spring:
  datasource:
    password: 1915970986z/3
    username: root
    url: jdbc:mysql://localhost:3306/bookmanager?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: spring-cloud-server-hello





mybatis:
  type-aliases-package: com.xhh.springcloudapi.model
  configuration:
    map-underscore-to-camel-case: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka,http://localhost1:7001/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    hostname: localhost